version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELK_VERSION
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELK_VERSION=${ELK_VERSION}
    ports:
      - "9200:9200"
      - "9300:9300"
    logging:
      driver: none
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:$ELK_VERSION
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELK_VERSION=${ELK_VERSION}
    restart: always
    logging:
      driver: none
    depends_on:
      - elasticsearch
